### PR TITLE
pulled in 2.38, which adds Python 3.0 support

### PR DESCRIPTION
**Pull request by bcoe**

### CODE REVIEW

**Comment by bcoe** [comment]
@mbmccoy, @kavdev mind giving 2.38 a shot? I've merged the latest code from SourceForge, and will publish to PyPi if it's looking good.

**Comment by mbmccoy** [comment]
Thanks for putting this together. A quick diff with my local copy shows one gnarly little bug that remains. I'll file an issue (with a workaround) momentarily.

**Comment by mbmccoy** [comment]
Tab error, line 2194.

**Comment by bcoe** [comment]
@mbmccoy I've published 2.38:

https://pypi.python.org/pypi/imaplib2

**Pull request merged**
