### PR TITLE
Use py_modules instead of packages and other updates

### PR DESCRIPTION
**Pull request by fmalina**
This should solve failing imports such as `from imaplib2 import IMAP4_SSL`.

### CODE REVIEW

**Comment by graingert** [comment]
This package works fine when installed from requirements.txt for me. Can you create a minimal failing example?

There's no supported python install without setuptools anymore. Setuptools + wheel is the current python packaging solution

**Comment by fmalina** [comment]
It might be the case that it didn't work correctly on Ubuntu, definitely didn't work for me, requirements.txt or not. Error reports from various other users are tucked in dark alleys of the web. Anyway py_modules is the correct semantics for distributing imaplib2.

Thanks for pointing it out the setuptools history, I was wondering why there was a comment instead of working code.

**Comment by graingert** [comment]
Can you link to an example of the failure? I'm on Ubuntu and this library installs fine

**Comment by fmalina** [comment]
Sorry no time for that.

Kind regards,
F. Malina
Founder Flatmate Rooms™ <https://www.flatmaterooms.co.uk>, etc.
<http://schooletc.co.uk>

+44 (0) 7715 342 265
3 School Drive, Billinge, WN57LR

**Comment by fmalina** [comment]
Installs fine, all is good than ;)

**Comment by graingert** [comment]
Cool, thanks for your pr

**Comment by fmalina** [comment]
That was a joke.

**Comment by bcoe** [comment]
@fmalina seems like @graingert closed this issue by mistake; the dangers of jokes having no tone on the Internet :)

Would love to get this working for you, but I'm not using imaplib2 (or Python) in production any longer. @graingert any thoughts about how we could get an appropriate test around this? perhaps there's additional information @fmalina could provide, to help us dig into this.

**Comment by fmalina** [comment]
I am sorry, I was reluctant to break my deployment just to find out what exactly is wrong now when it was fixed for some time by using imaplib2 directly from SourceForge.

With vanilla imaplib2 install you can do `from imaplib2 import IMAP4_SSL`. This is found in many examples on the web. With this package I get an import error. Rectified easily with `from imaplib2.imaplib2 ...` I know. I recently saw discussions about other applications broken in this way but could not find them anymore.

Aside: There is effort to upgrade imaplib in python standard library to imaplib2, discussed here http://bugs.python.org/issue11245. I though you may want to +1 that.

**Comment by fmalina** [comment]
Please merge.

**Comment by graingert** [comment]
Ah, I see what you mean: the `import *` is skipping objects not declared in
`__all__`.
From your description of the problem I thought you could not install the
library, then I thought you'd managed to fix this on your machine, sorry
for the misunderstanding.

This will need a test case though and this change will break everyone using
the workaround: `imaplib2.imaplib2`

Please do not change `setup.py` to import from a not-installed module just
for the version. It's fairly simple to pull this out manually and we don't
know if upstream will keep the value in `__version__`

**Comment by fmalina** [comment]
Importing from not installed module works as it is on the path during install and Piers always updates the __version__.  I'd prefer to break a hacky import now and keep it in line with original.

**Comment by graingert** [comment]
I've found the issue here, It's not because of the "import *" It's because in python 3

On python 2 the default is to relative import so:
```python
# impalib2/__init__.py
from imaplib2 import *
```

imports 'imaplib2/imaplib2.py', however on python 3 it imports 'imaplib2/__init__.py'

Please see #13 for the minimal fix and tests.

**Comment by fmalina** [comment]
Did you decide on the fix?

**Pull request closed without merging**
