### PR TITLE
Use absolute_imports in __init__.py

### PR DESCRIPTION
**Pull request by graingert**
Also add the latest Python gitignore that covers tox, and build detritus

This should fix #12

### CODE REVIEW

**Comment by fmalina** [comment]
That's a lot of debris. I find #12 fix more elegant, but than again I wrote it.
I know that support for python2 in imaplib is not a priority, not sure if it even works now.

**Comment by graingert** [comment]
@fmalina This isn't debris, it's framework for tests:

Debris | Use
------------ | -------------
.travis.yml | To use free CI system 'Travis CI'
tox.ini | Configuration for tox standardized testing in Python
.gitignore | The standard Python gitignore, to ignore files generated by tox and pytest

**Comment by fmalina** [comment]
Guido gave me some good advice 3 days ago: "...try working on your tone -- you... a bit passive-aggressive". I'd like to pass it on.

**Comment by bcoe** [comment]
@fmalina no need for anyone to use a tone that's anything other than friendly, If possible I'd like us all to take a step back and take a deep breath :)

I forked this library four years ago because I needed it to be published to a package manager, and I find GitHub to be a much better platform for collaboration than SourceForge. At the time I ran an email related startup, and I expected this repo would gradually deviate from Piers' awesome work.

We now find ourselves in 2015; it's obvious that more active work is being done on the mainline Imaplib2 again, and I'm happy to enter in discussion with Piers about transferring the PyPi module (thank you for the intro email).

Having said this, I think @graingert is taking great initiative with this repo: getting continuous integration in place, getting unit tests in place -- these are steps that make for a successful OSS project.

I think what it comes down to, is we need to figure out what happens to this repo -- I think a rename is probably in order, depending on how chatting with Piers goes.

**Pull request merged**
