### PR TITLE
Merge upstream v2.55 and track upstream

### PR DESCRIPTION
**Pull request by dhke**
Merge v2.55 from upstream.

**WARNING**: This also causes upstream history to be pulled in (for easier future merges), but I can also make a "clean" merge that only adds the modifications.

### CODE REVIEW

**Comment by graingert** [comment]
Use https://github.com/MarkLodato/git-reparent to make a pure merge commit

**Comment by graingert** [comment]
To be honest I'm almost not interested in accepting any of these unless upstream decides they want to participate in the rest of the Python community

**Comment by dhke** [comment]
Would you take a simple merge commit that only pulls in upstream changes? Albeit it looks like most of these are py3 updates, so I'd probably even diverge and check in only the bugfixes.

**Comment by graingert** [comment]
@dhke I don't want to diverge but I'd really like some sort of dialogue with upstream to start first.

**Comment by dhke** [comment]
Thanks, I'll try to make contact any maybe we can figure something out.

**Pull request closed without merging**
